---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  chart:
    spec:
      version: ">=0.18.0 <1.0.0"
  values:
    prometheus-node-exporter:
      enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubelinks
  namespace: kubelinks
spec:
  chart:
    spec:
      version: ">=0.0.1 <1.0.0"
