---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  chart:
    spec:
      version: "0.69.0"
      chart: victoria-metrics-k8s-stack
      sourceRef:
        kind: HelmRepository
        name: vm
  values:
    prometheus-node-exporter:
      hostRootFsMount:
        enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelinks
  namespace: kubelinks
spec:
  chart:
    spec:
      version: "0.4.13"
      chart: kubelinks
      sourceRef:
        kind: HelmRepository
        name: kkirara
        namespace: kubelinks
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-event-logger
  namespace: k8s-event-logger
spec:
  chart:
    spec:
      version: "1.1.8"
      chart: k8s-event-logger
      sourceRef:
        kind: HelmRepository
        name: deliveryhero
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  chart:
    spec:
      version: "3.13.0"
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: metrics-server
  values:
    args:
      - --kubelet-insecure-tls
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: blackbox-exporter
spec:
  chart:
    spec:
      version: "11.7.1"
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  chart:
    spec:
      version: "2.18.3"
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: kedacore
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      version: "1.28.3"
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress-private
  namespace: istio-ingress
spec:
  chart:
    spec:
      version: "1.28.3"
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-exporter
  namespace: helm-exporter
spec:
  chart:
    spec:
      version: "1.3.0+109c2ba"
      chart: helm-exporter
      sourceRef:
        kind: HelmRepository
        name: sstarcher
        namespace: helm-exporter
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  chart:
    spec:
      version: "0.27.0"
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      version: "v1.19.2"
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  chart:
    spec:
      version: "10.0.3"
      chart: reflector
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: reflector
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      version: "1.3.1"
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  chart:
    spec:
      version: "5.8.134"
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: jenkins
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  chart:
    spec:
      version: "9.4.1"
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: argocd
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: strimzi
spec:
  chart:
    spec:
      version: "0.50.0"
      chart: strimzi-kafka-operator
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: strimzi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin4
  namespace: pgadmin
spec:
  chart:
    spec:
      version: "1.57.0"
      chart: pgadmin4
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: pgadmin
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  chart:
    spec:
      version: "1.18.0"
      chart: airflow
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: airflow
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: operator
  namespace: minio-operator
spec:
  chart:
    spec:
      version: "7.1.1"
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  chart:
    spec:
      version: "6.51.0"
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki
  values:
    gateway:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: placeholder-flux-bug-label
              topologyKey: kubernetes.io/hostname
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: alloy
spec:
  chart:
    spec:
      version: "1.5.3"
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: elastic-system
spec:
  chart:
    spec:
      version: "3.2.0"
      chart: eck-operator
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: x509-certificate-exporter
  namespace: x509-certificate-exporter
spec:
  chart:
    spec:
      version: "3.19.1"
      chart: x509-certificate-exporter
      sourceRef:
        kind: HelmRepository
        name: enix
        namespace: x509-certificate-exporter
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  chart:
    spec:
      version: "2.2.7"
      chart: reloader
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: reloader
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: seaweedfs
#   namespace: seaweedfs
# spec:
#   chart:
#     spec:
#       version: "4.0.404"
#       chart: seaweedfs
#       sourceRef:
#         kind: HelmRepository
#         name: seaweedfs
#         namespace: seaweedfs
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse-operator
  namespace: clickhouse-operator
spec:
  chart:
    spec:
      version: "0.25.6"
      chart: altinity-clickhouse-operator
      sourceRef:
        kind: HelmRepository
        name: clickhouse-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vls
  namespace: victoria-logs
spec:
  chart:
    spec:
      version: "0.11.25"
      chart: victoria-logs-single
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: victoria-logs
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  chart:
    spec:
      version: "3.6.2"
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apache-superset
  namespace: apache-superset
spec:
  releaseName: apache-superset
  chart:
    spec:
      version: "0.15.2"
      chart: superset
      sourceRef:
        kind: HelmRepository
        name: superset
        namespace: apache-superset
