---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  chart:
    spec:
      version: ">=0.18.0 <1.0.0"
  values:
    prometheus-node-exporter:
      enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubelinks
  namespace: kubelinks
spec:
  chart:
    spec:
      version: ">=0.0.1 <1.0.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: k8s-event-logger
  namespace: k8s-event-logger
spec:
  chart:
    spec:
      version: ">=1.0.0 <2.0.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  chart:
    spec:
      version: ">=3.8.0 <4.0.0"
  values:
    args:
      - --kubelet-insecure-tls
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: blackbox-exporter
spec:
  chart:
    spec:
      version: ">=8.0.0 <9.0.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  chart:
    spec:
      version: ">=2.0.0 <3.0.0"
