apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/victoria-metrics-k8s-stack
  - ../../base/flux-monitoring
  - ../../base/kubelinks
  - ../../base/k8s-event-logger
  - ../../base/metrics-server
  - ../../base/blackbox-exporter
  - ../../base/keda
  - ../../base/istio
  - ../../base/helm-exporter
  - ../../base/cloudnative-pg
  - ../../base/cert-manager
  - ../../base/reflector
patchesStrategicMerge:
  - docker-flex.yaml
