apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/victoria-metrics-k8s-stack
  - ../../base/flux-monitoring
  - ../../base/kubelinks
  - ../../base/k8s-event-logger
  - ../../base/metrics-server
  - ../../base/blackbox-exporter
  - ../../base/keda
  - ../../base/istio
  - ../../base/helm-exporter
  - ../../base/cloudnative-pg
  - ../../base/cert-manager
  - ../../base/reflector
  - ../../base/external-secrets
  - ../../base/jenkins-server
  - ../../base/argocd
  - ../../base/strimzi
  - ../../base/pgadmin
  - ../../base/airflow
  - ../../base/capacitor
  - ../../base/minio-operator
  - ../../base/loki
  - ../../base/eck-operator
  - ../../base/oomkill-exporter
  - ../../base/x509-certificate-exporter
  - ../../base/reloader
  - ../../base/alloy
  - ../../base/dragonfly-operator
  - ../../base/seaweedfs
  - ../../base/clickhouse-operator
  - ../../base/httpbin
  - ../../base/kro
  - ../../base/victoria-logs
  - ../../base/kyverno
patches:
  - path: docker-flex.yaml
