apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: argocd
      interval: 5m
  releaseName: argocd
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 34
  # Default values: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
  values:
    global:
      domain: argocd.${cluster_subdomain}
      networkPolicy:
        create: true
    configs:
      params:
        server.insecure: true
    dex:
      enabled: false
