apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: oomkill-exporter
spec:
  podMetricsEndpoints:
    - port: metrics
      scheme: http
  selector:
    matchLabels:
      app: oomkill-exporter
