---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kubelinks-gateway
  namespace: kubelinks
spec:
  gatewayClassName: merged-eg
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: http
      port: 8080
      protocol: HTTP
