---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  chart:
    spec:
      version: "0.27.0"
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
  values:
    crds:
      create: false
    monitoring:
      podMonitorEnabled: false
      grafanaDashboard:
        create: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      version: "1.28.3"
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  values:
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress-private
  namespace: istio-ingress
spec:
  chart:
    spec:
      version: "1.28.3"
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin4
  namespace: pgadmin
spec:
  chart:
    spec:
      version: "1.56.1"
      chart: pgadmin4
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: pgadmin
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  chart:
    spec:
      version: "10.5.5"
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
  values:
    initChownData:
      securityContext:
        capabilities:
          drop: []
