---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: capacitor-virtualservice
spec:
  gateways:
    - istio-ingress/wildcard-gateway
  hosts:
    - capacitor.${cluster_subdomain}
  http:
    - route:
        - destination:
            host: capacitor
            port:
              number: 9000
