apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
configMapGenerator:
  - name: alloy-config
    namespace: alloy
    files:
      - config.alloy
    options:
      disableNameSuffixHash: true
      labels:
        kustomize.toolkit.fluxcd.io/substitute: disabled