apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - vm-rule.yaml
  - namespace.yaml
configMapGenerator:
  - name: blackbox-exporter-dashboards
    namespace: blackbox-exporter
    files:
      - blackbox-exporter.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: blackbox-exporter
        app.kubernetes.io/component: blackbox-exporter
        kustomize.toolkit.fluxcd.io/substitute: disabled
