---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-backstage
  namespace: pg-backstage
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  enableSuperuserAccess: true
  superuserSecret:
    name: pg-backstage-superuser
  storage:
    size: 10Gi
  monitoring:
    enablePodMonitor: true
