apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: ollama
spec:
  releaseName: open-webui
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: ollama
  interval: 15m
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Default webui values: https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/values.yaml
  # ollama sub-values: https://github.com/otwld/ollama-helm/blob/main/values.yaml
  values:
    ollama:
      ollama:
        gpu:
          enabled: true
          type: "nvidia"
          number: 1
        models:
          - llama3
        persistentVolume:
          enabled: true
