apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: encryption-secret-key
  namespace: n8n
spec:
  length: 16
  symbols: 0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: encryption-secret-key
  namespace: n8n
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: encryption-secret-key
    template:
      engineVersion: v2
      data:
        helm-release-values-secret: |
          main:
            config:
              n8n:
                encryption_key: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: encryption-secret-key
