apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  releaseName: n8n
  chartRef:
    kind: OCIRepository
    name: 8gears
    namespace: n8n
  interval: 15m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: encryption-secret-key
      valuesKey: helm-release-values-secret
  # Defaults: https://github.com/8gears/n8n-helm-chart/blob/main/charts/n8n/values.yaml
  values:
    main:
      config:
        config:
          db:
            type: postgresdb
            postgresdb:
              host: pg-n8n-rw.pg-n8n
              user: n8n
        extraEnv:
          DB_POSTGRESDB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: pg-n8n-user-secret
                key: password
