---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: n8n-virtualservice
  namespace: n8n
spec:
  gateways:
    - istio-ingress/wildcard-gateway
  hosts:
    - n8n.${cluster_subdomain}
  http:
    - route:
        - destination:
            host: n8n.n8n.svc.cluster.local
            port:
              number: 80
