apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator
spec:
  releaseName: elastic-operator
  chart:
    spec:
      chart: eck-operator
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic-system
  interval: 15m
  install:
    remediation:
      retries: 3
  # Default values: https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-operator/values.yaml
  valuesFrom:
  - kind: ConfigMap
    name: values-public