apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-exporter
  namespace: helm-exporter
spec:
  releaseName: helm-exporter
  chart:
    spec:
      chart: helm-exporter
      sourceRef:
        kind: HelmRepository
        name: sstarcher
        namespace: helm-exporter
  interval: 15m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Defaults: https://github.com/sstarcher/helm-exporter/blob/master/helm/values.yaml
  values:
    intervalDuration: 300s
    serviceMonitor:
      interval: 300s
      create: true
    podSecurityContext:
      fsGroup: 2000
    securityContext:
      #runAsUser: 1000
      runAsGroup: 2000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      #runAsNonRoot: true
    config:
      helmRegistries:
        override:
          - registry:
              url: "https://shanestarcher.com/helm-charts/"
            charts:
              - helm-exporter
          - registry:
              url: "https://kubernetes.github.io/autoscaler/"
            charts:
              - cluster-autoscaler
          - registry:
              url: "https://aws.github.io/eks-charts"
            charts:
              - aws-load-balancer-controller
          - registry:
              url: "https://charts.jetstack.io"
            charts:
              - cert-manager
          - registry:
              url: "https://kubernetes-sigs.github.io/external-dns/"
            charts:
              - external-dns
          - registry:
              url: "https://istio-release.storage.googleapis.com/charts"
            charts:
              - base
              - istiod
              - gateway
          - registry:
              url: "https://victoriametrics.github.io/helm-charts/"
            charts:
              - victoria-metrics-k8s-stack
          - registry:
              url: "https://kubernetes-sigs.github.io/metrics-server/"
            charts:
              - metrics-server
          - registry:
              url: "https://fluent.github.io/helm-charts"
            charts:
              - fluent-bit
          - registry:
              url: "https://kkirara.github.io/KubeLinks"
            charts:
              - kubelinks
          - registry:
              url: https://emberstack.github.io/helm-charts
            charts:
              - reflector
          - registry:
              url: https://charts.external-secrets.io
            charts:
              - external-secrets
          - registry:
              url: https://charts.deliveryhero.io
            charts:
              - k8s-event-logger
          - registry:
              url: https://kedacore.github.io/charts
            charts:
              - keda
          - registry:
              url: https://prometheus-community.github.io/helm-charts
            charts:
              - prometheus-blackbox-exporter
              - prometheus-operator-crds
          - registry:
              url: https://kubernetes-sigs.github.io/aws-efs-csi-driver
            charts:
              - aws-efs-csi-driver
          - registry:
              url: https://argoproj.github.io/argo-helm
            charts:
              - argo-cd
          - registry:
              url: https://app.getambassador.io
            charts:
              - telepresence
          - registry:
              url: https://cloudnative-pg.github.io/charts
            charts:
              - cloudnative-pg
          - registry:
              url: https://charts.jenkins.io
            charts:
              - jenkins
          - registry:
              url: https://strimzi.io/charts
            charts:
              - strimzi-kafka-operator
          - registry:
              url: https://helm.runix.net
            charts:
              - pgadmin4
          - registry:
              url: https://airflow.apache.org
            charts:
              - airflow
          - registry:
              url: https://operator.min.io
            charts:
              - operator
              - tenant
          - registry:
              url: https://grafana.github.io/helm-charts
            charts:
              - loki
              - promtail
