apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-exporter
spec:
  releaseName: helm-exporter
  chart:
    spec:
      chart: helm-exporter
      sourceRef:
        kind: HelmRepository
        name: sstarcher
        namespace: helm-exporter
  interval: 15m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Defaults: https://github.com/sstarcher/helm-exporter/blob/master/helm/values.yaml
  valuesFrom:
  - kind: ConfigMap
    name: values-public

