apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-read-only
rules:
  - apiGroups:
      - ""
      - "apps"
      - "autoscaling"
      - "batch"
    resources:
      - pods
      - deployments
      - replicasets
      - services
      - configmaps
      - limitranges
      - jobs
      - cronjobs
      - statefulsets
      - daemonsets
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-read-only-binding
subjects:
  - kind: ServiceAccount
    name: backstage-admin
    namespace: default
roleRef:
  kind: ClusterRole
  name: backstage-read-only
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-admin-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: backstage-admin
type: kubernetes.io/service-account-token
