apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apache-superset
  namespace: apache-superset
spec:
  releaseName: apache-superset
  chart:
    spec:
      chart: superset
      sourceRef:
        kind: HelmRepository
        name: superset
        namespace: http://apache.github.io/superset/
  interval: 5m
  install:
    remediation:
      retries: 3
  # Defaults: https://github.com/apache/superset/tree/master/helm/superset
  # values:
