apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apache-superset
  namespace: apache-superset
spec:
  releaseName: apache-superset
  chart:
    spec:
      chart: superset
      sourceRef:
        kind: HelmRepository
        name: superset
        namespace: apache-superset
  interval: 5m
  install:
    remediation:
      retries: 3
  # Defaults: https://github.com/apache/superset/blob/master/helm/superset/values.yaml
  values:
    bootstrapScript: |
      #!/bin/bash
      # Update system packages and install dependencies
      apt update && apt install -y gcc libpq-dev python3-dev pkg-config default-libmysqlclient-dev && \

      # Install Python dependencies
      pip install psycopg2-binary==2.9.10 \
        sqlalchemy-bigquery==1.14.1 \
        elasticsearch-dbapi==0.2.11 \
        mysqlclient && \
        mysql-connector

      # Create a bootstrap log file if not already created
      if [ ! -f ~/bootstrap ]; then
        echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap
      fi
    envFromSecrets:
      - secret-key
