apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: secret-key
  namespace: apache-superset
spec:
  length: 42
  symbols: 0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret-key
  namespace: apache-superset
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: secret-key
    template:
      engineVersion: v2
      data:
        SUPERSET_SECRET_KEY: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: secret-key
