apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  values:
    defaultRules:
      disabled:
        TooManyScrapeErrors: true
