apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  releaseName: airflow
  chart:
    spec:
      chart: airflow
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: airflow
  interval: 15m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Defaults: https://github.com/apache/airflow/blob/main/chart/values.yaml
  values:
    postgresql:
      enabled: false
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false
    data:
      metadataSecretName: pg-airflow-user-secret
    webserverSecretKeySecretName: webserver-secret-key
