apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
spec:
  releaseName: airflow
  chart:
    spec:
      chart: airflow
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
        namespace: airflow
  interval: 15m
  timeout: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Defaults: https://github.com/apache/airflow/blob/main/chart/values.yaml
  valuesFrom:
  - kind: ConfigMap
    name: values-public
