apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: webserver-secret-key
  namespace: airflow
spec:
  length: 16
  symbols: 0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webserver-secret-key
  namespace: airflow
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: webserver-secret-key
    template:
      engineVersion: v2
      data:
        webserver-secret-key: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: webserver-secret-key
