apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
spec:
  releaseName: cnpg
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
  interval: 5m
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
  # Default values: https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/values.yaml
  values:
    crds:
      create: false
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
