apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: pg-n8n-user-secret
  namespace: pg-n8n
spec:
  length: 24
  symbols: 0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-n8n-user-secret
  namespace: pg-n8n
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: pg-n8n-user-secret
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "n8n"
      data:
        username: n8n
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pg-n8n-user-secret
