---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelinks
  namespace: kubelinks
spec:
  chart:
    spec:
      version: "0.4.13"
      chart: kubelinks
      sourceRef:
        kind: HelmRepository
        name: kkirara
        namespace: kubelinks
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      version: "1.27.3"
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress-private
  namespace: istio-ingress
spec:
  chart:
    spec:
      version: "1.27.3"
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  chart:
    spec:
      version: "9.1.37"
      chart: reflector
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: reflector
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      version: "1.0.0"
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  chart:
    spec:
      version: "0.26.1"
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
