apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/istio
  - ../../base/external-secrets
  - ../../base/reflector
  - ../../base/cloudnative-pg
  - ../../base/n8n
  - ../../base/kubelinks
patches:
  - path: hetznerk3s.yaml
