---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-egressgateway
  namespace: istio-egressgateway
spec:
  releaseName: istio-egressgateway
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 5m
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
  # Default values: https://github.com/istio/istio/blob/master/manifests/charts/gateway/values.yaml
  values:
    service:
      type: ClusterIP
    autoscaling:
      minReplicas: 1
      maxReplicas: 4
