apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- namespace.yaml
  #- helm-repo.yaml
  - helm-release.yaml
  - helm-istio-gw-private.yaml
  #- helm-istio-gw-public.yaml
  - telemetry.yaml
  #- monitors.yaml
  #- prometheusrule.yaml
