apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-public
spec:
  releaseName: external-dns-public
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
  interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  # Defaults: https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml
  valuesFrom:
  - kind: ConfigMap
    name: values-public
