apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repo.yaml
  - helm-release-public.yaml
  - helm-release-private.yaml
  - vm-rule.yaml
configMapGenerator:
  - name: external-dns-dashboards
    namespace: external-dns
    files:
      - edns-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: external-dns
        app.kubernetes.io/component: external-dns
        kustomize.toolkit.fluxcd.io/substitute: disabled
