apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repo.yaml
  - helm-release.yaml
  - namespace.yaml
configMapGenerator:
  - name: clickhouse-grafana-dashboards
    namespace: clickhouse-operator
    files:
      - dashboards/Altinity_ClickHouse_Operator_dashboard.json
      - dashboards/ClickHouse_Queries_dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        kustomize.toolkit.fluxcd.io/substitute: disabled
