---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kubelinks-gateway
  namespace: kubelinks
spec:
  gatewayClassName: merged-eg
  listeners:
    - name: http
      port: 8080
      protocol: HTTP
    - name: https
      port: 8443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: localhost-direct
        mode: Terminate
