apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repo.yaml
  - helm-release.yaml
  - vm-rule.yaml
configMapGenerator:
  - name: external-secrets-dashboards
    namespace: external-secrets
    files:
      - eso-dashboard.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: external-secrets
        app.kubernetes.io/component: external-secrets
        kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
- kustomizeconfig.yaml
