apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
spec:
  interval: 15m
  timeout: 15m
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: kedacore
      interval: 5m
  releaseName: keda
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Default values: https://github.com/kedacore/charts/blob/main/keda/values.yaml
  valuesFrom:
  - kind: ConfigMap
    name: values-public
