apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin4
spec:
  releaseName: pgadmin4
  chart:
    spec:
      chart: pgadmin4
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: pgadmin
  interval: 5m
  install:
    remediation:
      retries: 3
  # Defaults: https://github.com/rowanruseler/helm-charts/blob/main/charts/pgadmin4/values.yaml
  # values:
