apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repo.yaml
  - helm-release.yaml
  - vm-rule.yaml
configMapGenerator:
- name: cluster-autoscaler-grafana-dashboards
  files:
    - dashboards/cluster-autoscaler.json
  options:
    disableNameSuffixHash: true
    labels:
      grafana_dashboard: "1"
      app.kubernetes.io/part-of: cluster-autoscaler
      app.kubernetes.io/component: monitoring
      kustomize.toolkit.fluxcd.io/substitute: disabled
- name: values-public
  files:
  - values.yaml=values-public.yaml
configurations:
- kustomizeconfig.yaml
namespace: kube-system