apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: loki
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.loki
        version: 1
        isDefault: false
        editable: false
        orgId: 1
        uid: loki
        jsonData:
          maxLines: 100
          timeout: 600
