apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  releaseName: loki
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki
  interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: minio-loki-env-configuration
      valuesKey: helm-release-loki-values
  # Default values: https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
  valuesFrom:
  - kind: ConfigMap
    name: values-public
