apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: minio-loki-user-secret
  namespace: minio-loki
spec:
  length: 24
  symbols: 0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-loki-user-secret
  namespace: minio-loki
spec:
  refreshInterval: 0s
  refreshPolicy: CreatedOnce
  target:
    name: minio-loki-env-configuration
    template:
      engineVersion: v2
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "loki"
      data:
        config.env: |
          export MINIO_ROOT_USER="minio"
          export MINIO_ROOT_PASSWORD="{{ .password }}"
        helm-release-loki-values: |
          loki:
            storage:
              s3:
                endpoint: https://minio.minio-loki.svc.cluster.local
                secretAccessKey: {{ .password }}
                accessKeyId: minio
                s3ForcePathStyle: true
                insecure: true
                http_config:
                  insecure_skip_verify: true
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: minio-loki-user-secret
