---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: minio-loki-virtualservice
  namespace: minio-loki
spec:
  gateways:
    - istio-ingress/wildcard-gateway
  hosts:
    - minio-loki.${cluster_subdomain}
  tls:
    - match:
        - port: 443
          sniHosts:
            - minio-loki.${cluster_subdomain}
      route:
        - destination:
            host: minio-loki-console.minio-loki.svc.cluster.local
            port:
              number: 9443
