apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github
  namespace: flux-system
spec:
  type: githubdispatch
  address: https://github.com/brainfair/awesome-flux-infra
  secretRef:
    name: flux-system
