apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
spec:
  releaseName: jenkins
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: jenkins
  interval: 5m
  timeout: 30m0s
  install:
    remediation:
      retries: 3
  # Defaults: https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml
  valuesFrom:
  - kind: ConfigMap
    name: values-public
