apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
spec:
  releaseName: jenkins
  chart:
    spec:
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: jenkins
  interval: 5m
  timeout: 30m0s
  install:
    remediation:
      retries: 3
  # Defaults: https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml
  values:
    controller:
      jenkinsUrl: jenkins.${cluster_subdomain}
      jenkinsUrlProtocol: "https"
      additionalPlugins:
        - azure-ad
        - ssh-agent
        - credentials-binding
        - timestamper
        - ws-cleanup
        - aws-credentials
        - pipeline-aws
        - jobConfigHistory
        - envinject
    agent:
      podTemplates:
        multitool: |
          - name: multitool
            label: multitool
            serviceAccount: jenkins-agent
            containers:
              - name: docker-awscli-kubectl
                image: guitarrapc/docker-awscli-kubectl
                command: "/bin/sh -c"
                args: "cat"
                ttyEnabled: true
                privileged: true
    serviceAccountAgent:
      create: true
