apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  chart:
    spec:
      version: "5.8.33"
      chart: jenkins
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: jenkins
