apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - oci-repo.yaml
  - helm-release.yaml
configurations:
- kustomizeconfig.yaml
configMapGenerator:
- name: values-public
  files:
  - values.yaml=values-public.yaml
namespace: dragonfly-operator-system